### ISSUE TITLE
Updating from 0.8.0 to 0.9.2 seems to have broken import paths

### ISSUE THREAD

**Issue by zoominGiladSher** [t3-oss/t3-env#204] opened 2024-03-04 12:03 UTC
Dependabot has suggested we update the package from `0.8.0` to `0.9.2`, however, the import of `createEnv` now fails -- please see the attached screenshots.

Worked before, not working now:

<img width="1080" alt="image" src="https://github.com/t3-oss/t3-env/assets/56221821/05972f16-f0c6-446c-8964-5a6b647e6fa4">

New import path required:

<img width="1080" alt="image" src="https://github.com/t3-oss/t3-env/assets/56221821/63ea19bd-09b1-4b63-9d32-226ba4580f0f">

I suspect that removing support for CJS and the changing of `package.json` in the last several commits may have caused it but I admit that I didn't have time to dive too deeply into it. Would appreciate you taking a look into it!

Thanks

**Comment by wottpal** [comment] 2024-03-11 07:32
Same here. ✋
Using `bun`, in case that matters.

**Comment by juliusmarminge** [comment] 2024-03-13 16:50
This is likely cause you have `node` as your module resolution. Change it to something more modern (`Node16`/`NodeNext` if transpiling with tsc, `Bundler` if using a bundler) that can read exports condition and you should be fine.

Duplicate of #189

**Closed by juliusmarminge** 2024-03-13 16:50 UTC
